image:
  - Visual Studio 2017
  - x64
clone_folder: c:\projects\hello_travis
build_script:
- cmd: >-
    mkdir c:\projects\hello_travis\build
    cd c:\projects\hello_travis\build

    cmake c:\projects\hello_travis -G "Visual Studio 15"

    cmake --build . --config "Debug"
test_script:
- cmd: ctest -C Debug
