image:
  - Visual Studio 2017
platform:
  - x64
clone_folder: c:\projects\hello_travis
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - >
    cmake %APPVEYOR_BUILD_FOLDER&\src
    -G "%generator%""
    cmake c:\projects\hello_travis -G "Visual Studio 15"
    cmake --build . --config "Debug"
test_script:
  - cmd: ctest -C Debug
