image:
  - Visual Studio 2017

configuration:
- Release
- Debug

platform:
  - x64

clone_folder: c:\projects\hello-travis

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake c:\projects\hello-travis -G"Visual Studio 15 2017"

build_script:
- cmd: >-
    cmake --build . --config "%configuration%"

test_script:
- cmd: |-
    cd test
    ctest -C Debug
