dist: trusty
sudo: false
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      # script:
      #   - cmake -DENABLE_COVERAGE:BOOL=TRUE -DENABLE_WERROR:BOOL=FALSE .
      #   - cmake --build . -- -j2
      #   - cd test
      #   - ctest -V
      #   - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-8
      after_success:
        - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-8

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - g++8
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

before_install:
  - eval "${MATRIX_EVAL}"
script:
  - cmake -DENABLE_COVERAGE:BOOL=TRUE -DENABLE_ASAN:BOOL=TRUE -DENABLE_WERROR:BOOL=FALSE .
  - cmake --build . -- -j2
  - cd test
  - ctest -V
