dist: trusty
sudo: required  # workaround to LSAN reporting a false positive
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - Cvr=FALSE
        - Asn=TRUE

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - Cvr=TRUE
        - Asn=TRUE
      after_success:
        - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-8

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - g++8
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
        - Cvr=FALSE
        - Asn=TRUE

# These steps will be executed for every 'include' in the matrix,
# They can be ovrriden by specifying the steps explicitly in a matrix include entry
# Other steps can be given on a case-by-case basis
#   -> g++-8 include has an additional after_success step
before_install:
  - eval "${MATRIX_EVAL}"
script:
  - cmake -DENABLE_COVERAGE:BOOL=${Cvr} -DENABLE_ASAN:BOOL=${Asn} -DENABLE_WERROR:BOOL=FALSE .
  - cmake --build . -- -j2
  - cd test
  - ctest -V -j2
